#!/usr/bin/env bash
# Copy only the files that belong in a public git repository into a new,
# empty directory. Nothing is deleted or modified in the source tree.
#
#   scripts/make-clean-copy.sh [destination]
#   scripts/make-clean-copy.sh --dry-run [destination]
#
# Default destination: ../compresscompare
#
# Excluded: build trees, fetched dependency sources, the signed .app bundle,
# IDE state, macOS metadata, and scratch directories — everything that either
# regenerates from source or leaks local absolute paths.

set -euo pipefail

DRY_RUN=0
if [ "${1-}" = "--dry-run" ]; then
  DRY_RUN=1
  shift
fi

SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEST="${1:-$(dirname "$SRC")/compresscompare}"

printf '\nSource:      %s\n' "$SRC"
printf 'Destination: %s\n\n' "$DEST"

# ---- Safety ----------------------------------------------------------------
if [ "$DEST" = "$SRC" ]; then
  echo "Destination must differ from the source tree." >&2
  exit 1
fi
case "$DEST" in
  "$SRC"/*)
    echo "Destination must not be inside the source tree." >&2
    exit 1
    ;;
esac
if [ -e "$DEST" ] && [ -n "$(ls -A "$DEST" 2>/dev/null)" ]; then
  echo "Destination exists and is not empty. Choose another path." >&2
  exit 1
fi

# ---- What to leave behind --------------------------------------------------
EXCLUDES=(
  # Build output — regenerated by scripts/build-macos.sh
  "build/"
  "cmake-build-*/"
  "out/"
  # Fetched dependency sources — restored by scripts/build-deps.sh
  "deps/"
  # Signed .app bundle plus a duplicate docs tree. Ship via GitHub Releases.
  "dist/"
  # IDE state; workspace.xml carries local paths and session data
  ".idea/"
  ".vscode/"
  "compile_commands.json"
  # macOS metadata
  ".DS_Store"
  "._*"
  # Scratch
  "Claude outputs/"
  # Superseded by .gitignore in the clean copy (handled below)
  ".gitignore.proposed"
  # Never copy an existing history into a "clean" tree
  ".git/"
)

RSYNC_ARGS=(-a --human-readable)
for e in "${EXCLUDES[@]}"; do
  RSYNC_ARGS+=(--exclude "$e")
done

if [ "$DRY_RUN" -eq 1 ]; then
  RSYNC_ARGS+=(--dry-run --itemize-changes)
  echo "DRY RUN — nothing will be written."
  echo
fi

mkdir -p "$DEST"
rsync "${RSYNC_ARGS[@]}" "$SRC"/ "$DEST"/

if [ "$DRY_RUN" -eq 1 ]; then
  echo
  echo "Dry run complete. Re-run without --dry-run to copy."
  exit 0
fi

# ---- Adopt the reviewed .gitignore ----------------------------------------
if [ -f "$SRC/.gitignore.proposed" ]; then
  cp "$SRC/.gitignore.proposed" "$DEST/.gitignore"
  echo
  echo "Note: .gitignore.proposed was installed as .gitignore in the copy."
  echo "      Your original is still at $SRC/.gitignore — diff if unsure."
fi

# ---- Executable bits -------------------------------------------------------
chmod +x "$DEST"/scripts/*.sh 2>/dev/null || true

# ---- Place for the CI workflows -------------------------------------------
mkdir -p "$DEST/.github/workflows"

# ---- Report ----------------------------------------------------------------
echo
echo "---------------------------------------------------------------"
printf 'Copied:  %s\n' "$(du -sh "$DEST" | cut -f1)"
printf 'Files:   %s\n' "$(find "$DEST" -type f | wc -l | tr -d ' ')"
echo "---------------------------------------------------------------"
echo
echo "Top level:"
ls -A "$DEST" | sed 's/^/  /'

# ---- Residual leak check ---------------------------------------------------
echo
leaks=$(grep -rlI -E "/(Users|home)/[a-zA-Z0-9._-]+/" "$DEST" 2>/dev/null || true)
if [ -n "$leaks" ]; then
  echo "WARNING — local absolute paths found in the copy:"
  echo "$leaks" | sed 's/^/  /'
  echo "  Review these before publishing."
else
  echo "No local absolute paths found in the copy."
fi

big=$(find "$DEST" -type f -size +5M 2>/dev/null || true)
if [ -n "$big" ]; then
  echo
  echo "Files over 5MB (each needs a conscious decision):"
  echo "$big" | while read -r f; do
    printf '  %s  %s\n' "$(du -h "$f" | cut -f1)" "${f#"$DEST"/}"
  done
fi

cat <<'NEXT'

Next steps
----------
  1. Copy codeql.yml and ci.yml into .github/workflows/ in the new directory.
  2. cd into the new directory, then:

       git init
       git add .
       scripts/preflight.sh      # before committing, not after
       git commit -m "Initial commit"

  3. Verify the build still works from the clean tree:

       scripts/build-macos.sh

NEXT
