#!/usr/bin/env python3
"""Generates docs/reference/sites.md from the `sites` list in config/config.yaml.

Running it after editing the site database keeps the reference page in step
with the file the executable actually embeds:

    python3 tools/gen_site_reference.py

It needs no third-party modules: the small YAML subset the `sites` list uses
(block list of maps, flow lists, plain, quoted and folded scalars) is read by a
purpose-built parser, and the script fails loudly on anything else.
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
YAML_PATH = ROOT / "config" / "config.yaml"
OUT_PATH = ROOT / "docs" / "reference" / "sites.md"

SITE_KEYS = ("name", "aliases", "hosts", "notes")


def strip_comment(line: str) -> str:
    """Removes a trailing ` # comment` outside quotes."""
    out, quote = "", None
    for i, ch in enumerate(line):
        if quote is None and ch == "#" and (i == 0 or line[i - 1] in " \t"):
            break
        if ch in "\"'" and quote is None:
            quote = ch
        elif ch == quote:
            quote = None
        out += ch
    return out.rstrip()


def scalar(value: str) -> str:
    """Turns a plain or quoted YAML scalar into text."""
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
        return value[1:-1]
    return value


def flow_list(value: str, where: str) -> list:
    """Parses `[a, b, c]`."""
    value = value.strip()
    if not (value.startswith("[") and value.endswith("]")):
        sys.exit(f"gen_site_reference: {where}: expected a flow list like [a, b]")
    inner = value[1:-1].strip()
    return [scalar(item) for item in inner.split(",") if item.strip()] if inner else []


def site_lines(text: str) -> list:
    """Returns the lines of the top-level `sites:` block."""
    lines = text.split("\n")
    for i, line in enumerate(lines):
        if re.match(r"sites:", line):
            return lines[i + 1:]
    sys.exit("gen_site_reference: no top-level `sites:` key in config.yaml")


def folded(lines: list, start: int, indent: int) -> tuple:
    """Joins a `>-` block that starts at `start`; returns (text, next index)."""
    parts = []
    i = start
    while i < len(lines):
        raw = lines[i]
        if raw.strip() == "":
            i += 1
            continue
        if len(raw) - len(raw.lstrip(" ")) <= indent:
            break
        parts.append(raw.strip())
        i += 1
    return " ".join(parts), i


def parse_sites(text: str) -> list:
    """Reads the `sites` list into a list of dicts with the four site keys."""
    lines = site_lines(text)
    sites, current, i = [], None, 0
    while i < len(lines):
        raw = strip_comment(lines[i])
        if raw.strip() == "":
            i += 1
            continue
        indent = len(raw) - len(raw.lstrip(" "))
        if indent == 0:
            break  # another top-level key
        body = raw.strip()
        if body.startswith("- "):
            current = {"name": "", "aliases": [], "hosts": [], "notes": ""}
            sites.append(current)
            body = body[2:].strip()
            indent += 2
        m = re.match(r"(\w+):\s*(.*)$", body)
        if not m or current is None:
            sys.exit(f"gen_site_reference: cannot read line {i + 1} of the sites block: {raw!r}")
        key, value = m.group(1), m.group(2)
        if key not in SITE_KEYS:
            sys.exit(f"gen_site_reference: unknown site key '{key}'")
        if key in ("aliases", "hosts"):
            current[key] = flow_list(value, f"{current['name'] or '?'}.{key}")
        elif value.strip() in (">-", ">", "|", "|-"):
            current[key], i = folded(lines, i + 1, indent)
            continue
        else:
            current[key] = scalar(value)
        i += 1
    if not sites:
        sys.exit("gen_site_reference: the sites list is empty")
    return sites


def cell(text: str) -> str:
    """Escapes a value for a markdown table cell."""
    return text.replace("|", "\\|")


def main() -> None:
    sites = parse_sites(YAML_PATH.read_text(encoding="utf-8"))
    lines = [
        "# Built-in site database",
        "",
        "*Generated by `tools/gen_site_reference.py` from the `sites` list in `config/config.yaml`; edit that",
        "file, not this page.*",
        "",
        f"The executable embeds these {len(sites)} entries. An override `config.yaml` can change any field of an",
        "entry (matched by name, case-insensitively) or append new entries – see",
        "[how to add or edit a site](../how-to/add-a-site.md).",
        "",
        "- **Name** is the label in the dropdown, the slot header and the exported file name.",
        "- **Aliases** are extra spellings the fuzzy search matches (`ig` → Instagram); the name itself always",
        "  matches.",
        "- **Hosts** are domain suffixes: a pasted URL whose host equals one of them, or ends in `.` + one of",
        "  them, selects the site automatically (longest suffix wins). An empty list means never auto-detected.",
        "- **Notes** are what the site typically does to uploads, shown when you hover a site name. They describe",
        "  behaviour observed in 2026 and change without notice; the measured numbers are the truth.",
        "",
        "| # | Name | Aliases | Hosts | Notes |",
        "|---|---|---|---|---|",
    ]
    for i, s in enumerate(sites):
        if not s["name"]:
            sys.exit(f"gen_site_reference: site {i} has no name")
        aliases = ", ".join(f"`{a}`" for a in s["aliases"]) or "–"
        hosts = ", ".join(f"`{h}`" for h in s["hosts"]) or "–"
        lines.append(f"| {i} | {cell(s['name'])} | {aliases} | {hosts} | {cell(s['notes'])} |")
    lines.append("")
    OUT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT_PATH.relative_to(ROOT)} ({len(sites)} sites)")


if __name__ == "__main__":
    main()
