# Embeds a file into a C++ header as a NUL-terminated unsigned char array.
#
# Usage (from add_custom_command):
#   cmake -DINPUT=<file> -DOUTPUT=<header> -DSYMBOL=<identifier> -P EmbedFile.cmake
#
# A byte array is used instead of a raw string literal because MSVC caps a
# single string literal at 16 KiB, which config.yaml already exceeds.

if(NOT INPUT OR NOT OUTPUT OR NOT SYMBOL)
  message(FATAL_ERROR "EmbedFile.cmake needs -DINPUT, -DOUTPUT and -DSYMBOL")
endif()

file(READ "${INPUT}" _hex HEX)
string(LENGTH "${_hex}" _hex_length)
math(EXPR _byte_count "${_hex_length} / 2")

string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _body "${_hex}")
# one line per 16 bytes keeps the header readable and every line short
string(REGEX REPLACE "((0x[0-9a-f][0-9a-f],){16})" "\\1\n  " _body "${_body}")

get_filename_component(_input_name "${INPUT}" NAME)
set(_content "/**
 * @file ${SYMBOL}.h
 * @brief ${_input_name} embedded as bytes.  Generated by cmake/EmbedFile.cmake; do not edit.
 */
#pragma once

#include <cstddef>

namespace cc {
namespace generated {

/** @brief The bytes of ${_input_name} followed by a terminating NUL. */
constexpr unsigned char ${SYMBOL}[] = {
  ${_body}0x00 };

/** @brief Number of bytes in ${_input_name}, excluding the terminating NUL. */
constexpr std::size_t ${SYMBOL}_size = ${_byte_count};

} // namespace generated
} // namespace cc
")

file(WRITE "${OUTPUT}.tmp" "${_content}")
execute_process(COMMAND "${CMAKE_COMMAND}" -E copy_if_different "${OUTPUT}.tmp" "${OUTPUT}")
file(REMOVE "${OUTPUT}.tmp")
